=begin
#Consolidate Services

#Description of all APIs

OpenAPI spec version: version not set

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.32-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ArgoCD::CertificateServiceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CertificateServiceApi' do
  before do
    # run before each test
    @instance = ArgoCD::CertificateServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CertificateServiceApi' do
    it 'should create an instance of CertificateServiceApi' do
      expect(@instance).to be_instance_of(ArgoCD::CertificateServiceApi)
    end
  end

  # unit tests for certificate_service_create_certificate
  # Creates repository certificates on the server
  # @param body List of certificates to be created
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :upsert Whether to upsert already existing certificates.
  # @return [V1alpha1RepositoryCertificateList]
  describe 'certificate_service_create_certificate test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for certificate_service_delete_certificate
  # Delete the certificates that match the RepositoryCertificateQuery
  # @param [Hash] opts the optional parameters
  # @option opts [String] :host_name_pattern A file-glob pattern (not regular expression) the host name has to match.
  # @option opts [String] :cert_type The type of the certificate to match (ssh or https).
  # @option opts [String] :cert_sub_type The sub type of the certificate to match (protocol dependent, usually only used for ssh certs).
  # @return [V1alpha1RepositoryCertificateList]
  describe 'certificate_service_delete_certificate test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for certificate_service_list_certificates
  # List all available repository certificates
  # @param [Hash] opts the optional parameters
  # @option opts [String] :host_name_pattern A file-glob pattern (not regular expression) the host name has to match.
  # @option opts [String] :cert_type The type of the certificate to match (ssh or https).
  # @option opts [String] :cert_sub_type The sub type of the certificate to match (protocol dependent, usually only used for ssh certs).
  # @return [V1alpha1RepositoryCertificateList]
  describe 'certificate_service_list_certificates test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
