=begin
#Consolidate Services

#Description of all APIs

OpenAPI spec version: version not set

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.32-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ArgoCD::GPGKeyServiceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GPGKeyServiceApi' do
  before do
    # run before each test
    @instance = ArgoCD::GPGKeyServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GPGKeyServiceApi' do
    it 'should create an instance of GPGKeyServiceApi' do
      expect(@instance).to be_instance_of(ArgoCD::GPGKeyServiceApi)
    end
  end

  # unit tests for g_pg_key_service_create
  # Create one or more GPG public keys in the server&#39;s configuration
  # @param body Raw key data of the GPG key(s) to create
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :upsert Whether to upsert already existing public keys.
  # @return [GpgkeyGnuPGPublicKeyCreateResponse]
  describe 'g_pg_key_service_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for g_pg_key_service_delete
  # Delete specified GPG public key from the server&#39;s configuration
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_id The GPG key ID to query for.
  # @return [GpgkeyGnuPGPublicKeyResponse]
  describe 'g_pg_key_service_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for g_pg_key_service_get
  # Get information about specified GPG public key from the server
  # @param key_id The GPG key ID to query for
  # @param [Hash] opts the optional parameters
  # @return [V1alpha1GnuPGPublicKey]
  describe 'g_pg_key_service_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for g_pg_key_service_list
  # List all available repository certificates
  # @param [Hash] opts the optional parameters
  # @option opts [String] :key_id The GPG key ID to query for.
  # @return [V1alpha1GnuPGPublicKeyList]
  describe 'g_pg_key_service_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
