=begin
#Consolidate Services

#Description of all APIs

OpenAPI spec version: version not set

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.32-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ArgoCD::NotificationServiceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NotificationServiceApi' do
  before do
    # run before each test
    @instance = ArgoCD::NotificationServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NotificationServiceApi' do
    it 'should create an instance of NotificationServiceApi' do
      expect(@instance).to be_instance_of(ArgoCD::NotificationServiceApi)
    end
  end

  # unit tests for notification_service_list_services
  # List returns list of services
  # @param [Hash] opts the optional parameters
  # @return [NotificationServiceList]
  describe 'notification_service_list_services test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for notification_service_list_templates
  # List returns list of templates
  # @param [Hash] opts the optional parameters
  # @return [NotificationTemplateList]
  describe 'notification_service_list_templates test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for notification_service_list_triggers
  # List returns list of triggers
  # @param [Hash] opts the optional parameters
  # @return [NotificationTriggerList]
  describe 'notification_service_list_triggers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
