=begin
#Consolidate Services

#Description of all APIs

OpenAPI spec version: version not set

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.32-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ArgoCD::RepoCredsServiceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RepoCredsServiceApi' do
  before do
    # run before each test
    @instance = ArgoCD::RepoCredsServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RepoCredsServiceApi' do
    it 'should create an instance of RepoCredsServiceApi' do
      expect(@instance).to be_instance_of(ArgoCD::RepoCredsServiceApi)
    end
  end

  # unit tests for repo_creds_service_create_repository_credentials
  # CreateRepositoryCredentials creates a new repository credential set
  # @param body Repository definition
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :upsert Whether to create in upsert mode.
  # @return [V1alpha1RepoCreds]
  describe 'repo_creds_service_create_repository_credentials test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repo_creds_service_delete_repository_credentials
  # DeleteRepositoryCredentials deletes a repository credential set from the configuration
  # @param url 
  # @param [Hash] opts the optional parameters
  # @return [RepocredsRepoCredsResponse]
  describe 'repo_creds_service_delete_repository_credentials test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repo_creds_service_list_repository_credentials
  # ListRepositoryCredentials gets a list of all configured repository credential sets
  # @param [Hash] opts the optional parameters
  # @option opts [String] :url Repo URL for query.
  # @return [V1alpha1RepoCredsList]
  describe 'repo_creds_service_list_repository_credentials test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for repo_creds_service_update_repository_credentials
  # UpdateRepositoryCredentials updates a repository credential set
  # @param creds_url URL is the URL that this credentials matches to
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [V1alpha1RepoCreds]
  describe 'repo_creds_service_update_repository_credentials test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
