=begin
#Consolidate Services

#Description of all APIs

OpenAPI spec version: version not set

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.32-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ArgoCD::SessionServiceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SessionServiceApi' do
  before do
    # run before each test
    @instance = ArgoCD::SessionServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SessionServiceApi' do
    it 'should create an instance of SessionServiceApi' do
      expect(@instance).to be_instance_of(ArgoCD::SessionServiceApi)
    end
  end

  # unit tests for session_service_create
  # Create a new JWT for authentication and set a cookie if using HTTP
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [SessionSessionResponse]
  describe 'session_service_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for session_service_delete
  # Delete an existing JWT cookie if using HTTP
  # @param [Hash] opts the optional parameters
  # @return [SessionSessionResponse]
  describe 'session_service_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for session_service_get_user_info
  # Get the current user&#39;s info
  # @param [Hash] opts the optional parameters
  # @return [SessionGetUserInfoResponse]
  describe 'session_service_get_user_info test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
