=begin
#Consolidate Services

#Description of all APIs

OpenAPI spec version: version not set

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.32-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ArgoCD::RepositoryDirectoryAppSpec
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RepositoryDirectoryAppSpec' do
  before do
    # run before each test
    @instance = ArgoCD::RepositoryDirectoryAppSpec.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RepositoryDirectoryAppSpec' do
    it 'should create an instance of RepositoryDirectoryAppSpec' do
      expect(@instance).to be_instance_of(ArgoCD::RepositoryDirectoryAppSpec)
    end
  end
end
