=begin
#Consolidate Services

#Description of all APIs

OpenAPI spec version: version not set

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.32-SNAPSHOT

=end

require 'date'

module ArgoCD
  class ApplicationApplicationSyncRequest
    attr_accessor :app_namespace

    attr_accessor :dry_run

    attr_accessor :infos

    attr_accessor :manifests

    attr_accessor :name

    attr_accessor :prune

    attr_accessor :resources

    attr_accessor :retry_strategy

    attr_accessor :revision

    attr_accessor :strategy

    attr_accessor :sync_options

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'app_namespace' => :'appNamespace',
        :'dry_run' => :'dryRun',
        :'infos' => :'infos',
        :'manifests' => :'manifests',
        :'name' => :'name',
        :'prune' => :'prune',
        :'resources' => :'resources',
        :'retry_strategy' => :'retryStrategy',
        :'revision' => :'revision',
        :'strategy' => :'strategy',
        :'sync_options' => :'syncOptions'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'app_namespace' => :'String',
        :'dry_run' => :'BOOLEAN',
        :'infos' => :'Array<V1alpha1Info>',
        :'manifests' => :'Array<String>',
        :'name' => :'String',
        :'prune' => :'BOOLEAN',
        :'resources' => :'Array<V1alpha1SyncOperationResource>',
        :'retry_strategy' => :'V1alpha1RetryStrategy',
        :'revision' => :'String',
        :'strategy' => :'V1alpha1SyncStrategy',
        :'sync_options' => :'ApplicationSyncOptions'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'appNamespace')
        self.app_namespace = attributes[:'appNamespace']
      end

      if attributes.has_key?(:'dryRun')
        self.dry_run = attributes[:'dryRun']
      end

      if attributes.has_key?(:'infos')
        if (value = attributes[:'infos']).is_a?(Array)
          self.infos = value
        end
      end

      if attributes.has_key?(:'manifests')
        if (value = attributes[:'manifests']).is_a?(Array)
          self.manifests = value
        end
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'prune')
        self.prune = attributes[:'prune']
      end

      if attributes.has_key?(:'resources')
        if (value = attributes[:'resources']).is_a?(Array)
          self.resources = value
        end
      end

      if attributes.has_key?(:'retryStrategy')
        self.retry_strategy = attributes[:'retryStrategy']
      end

      if attributes.has_key?(:'revision')
        self.revision = attributes[:'revision']
      end

      if attributes.has_key?(:'strategy')
        self.strategy = attributes[:'strategy']
      end

      if attributes.has_key?(:'syncOptions')
        self.sync_options = attributes[:'syncOptions']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          app_namespace == o.app_namespace &&
          dry_run == o.dry_run &&
          infos == o.infos &&
          manifests == o.manifests &&
          name == o.name &&
          prune == o.prune &&
          resources == o.resources &&
          retry_strategy == o.retry_strategy &&
          revision == o.revision &&
          strategy == o.strategy &&
          sync_options == o.sync_options
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [app_namespace, dry_run, infos, manifests, name, prune, resources, retry_strategy, revision, strategy, sync_options].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = ArgoCD.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
