=begin
#Consolidate Services

#Description of all APIs

OpenAPI spec version: version not set

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.32-SNAPSHOT

=end

require 'date'

module ArgoCD
  # SCMProviderGenerator defines a generator that scrapes a SCMaaS API to find candidate repos.
  class V1alpha1SCMProviderGenerator
    attr_accessor :azure_dev_ops

    attr_accessor :bitbucket

    attr_accessor :bitbucket_server

    # Which protocol to use for the SCM URL. Default is provider-specific but ssh if possible. Not all providers necessarily support all protocols.
    attr_accessor :clone_protocol

    # Filters for which repos should be considered.
    attr_accessor :filters

    attr_accessor :gitea

    attr_accessor :github

    attr_accessor :gitlab

    # Standard parameters.
    attr_accessor :requeue_after_seconds

    attr_accessor :template

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'azure_dev_ops' => :'azureDevOps',
        :'bitbucket' => :'bitbucket',
        :'bitbucket_server' => :'bitbucketServer',
        :'clone_protocol' => :'cloneProtocol',
        :'filters' => :'filters',
        :'gitea' => :'gitea',
        :'github' => :'github',
        :'gitlab' => :'gitlab',
        :'requeue_after_seconds' => :'requeueAfterSeconds',
        :'template' => :'template'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'azure_dev_ops' => :'V1alpha1SCMProviderGeneratorAzureDevOps',
        :'bitbucket' => :'V1alpha1SCMProviderGeneratorBitbucket',
        :'bitbucket_server' => :'V1alpha1SCMProviderGeneratorBitbucketServer',
        :'clone_protocol' => :'String',
        :'filters' => :'Array<V1alpha1SCMProviderGeneratorFilter>',
        :'gitea' => :'V1alpha1SCMProviderGeneratorGitea',
        :'github' => :'V1alpha1SCMProviderGeneratorGithub',
        :'gitlab' => :'V1alpha1SCMProviderGeneratorGitlab',
        :'requeue_after_seconds' => :'String',
        :'template' => :'V1alpha1ApplicationSetTemplate'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'azureDevOps')
        self.azure_dev_ops = attributes[:'azureDevOps']
      end

      if attributes.has_key?(:'bitbucket')
        self.bitbucket = attributes[:'bitbucket']
      end

      if attributes.has_key?(:'bitbucketServer')
        self.bitbucket_server = attributes[:'bitbucketServer']
      end

      if attributes.has_key?(:'cloneProtocol')
        self.clone_protocol = attributes[:'cloneProtocol']
      end

      if attributes.has_key?(:'filters')
        if (value = attributes[:'filters']).is_a?(Array)
          self.filters = value
        end
      end

      if attributes.has_key?(:'gitea')
        self.gitea = attributes[:'gitea']
      end

      if attributes.has_key?(:'github')
        self.github = attributes[:'github']
      end

      if attributes.has_key?(:'gitlab')
        self.gitlab = attributes[:'gitlab']
      end

      if attributes.has_key?(:'requeueAfterSeconds')
        self.requeue_after_seconds = attributes[:'requeueAfterSeconds']
      end

      if attributes.has_key?(:'template')
        self.template = attributes[:'template']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          azure_dev_ops == o.azure_dev_ops &&
          bitbucket == o.bitbucket &&
          bitbucket_server == o.bitbucket_server &&
          clone_protocol == o.clone_protocol &&
          filters == o.filters &&
          gitea == o.gitea &&
          github == o.github &&
          gitlab == o.gitlab &&
          requeue_after_seconds == o.requeue_after_seconds &&
          template == o.template
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [azure_dev_ops, bitbucket, bitbucket_server, clone_protocol, filters, gitea, github, gitlab, requeue_after_seconds, template].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = ArgoCD.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
