=begin
#Consolidate Services

#Description of all APIs

OpenAPI spec version: version not set

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.32-SNAPSHOT

=end

require 'date'

module ArgoCD
  class VersionVersionMessage
    attr_accessor :build_date

    attr_accessor :compiler

    attr_accessor :git_commit

    attr_accessor :git_tag

    attr_accessor :git_tree_state

    attr_accessor :go_version

    attr_accessor :helm_version

    attr_accessor :jsonnet_version

    attr_accessor :kubectl_version

    attr_accessor :kustomize_version

    attr_accessor :platform

    attr_accessor :version

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'build_date' => :'BuildDate',
        :'compiler' => :'Compiler',
        :'git_commit' => :'GitCommit',
        :'git_tag' => :'GitTag',
        :'git_tree_state' => :'GitTreeState',
        :'go_version' => :'GoVersion',
        :'helm_version' => :'HelmVersion',
        :'jsonnet_version' => :'JsonnetVersion',
        :'kubectl_version' => :'KubectlVersion',
        :'kustomize_version' => :'KustomizeVersion',
        :'platform' => :'Platform',
        :'version' => :'Version'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'build_date' => :'String',
        :'compiler' => :'String',
        :'git_commit' => :'String',
        :'git_tag' => :'String',
        :'git_tree_state' => :'String',
        :'go_version' => :'String',
        :'helm_version' => :'String',
        :'jsonnet_version' => :'String',
        :'kubectl_version' => :'String',
        :'kustomize_version' => :'String',
        :'platform' => :'String',
        :'version' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'BuildDate')
        self.build_date = attributes[:'BuildDate']
      end

      if attributes.has_key?(:'Compiler')
        self.compiler = attributes[:'Compiler']
      end

      if attributes.has_key?(:'GitCommit')
        self.git_commit = attributes[:'GitCommit']
      end

      if attributes.has_key?(:'GitTag')
        self.git_tag = attributes[:'GitTag']
      end

      if attributes.has_key?(:'GitTreeState')
        self.git_tree_state = attributes[:'GitTreeState']
      end

      if attributes.has_key?(:'GoVersion')
        self.go_version = attributes[:'GoVersion']
      end

      if attributes.has_key?(:'HelmVersion')
        self.helm_version = attributes[:'HelmVersion']
      end

      if attributes.has_key?(:'JsonnetVersion')
        self.jsonnet_version = attributes[:'JsonnetVersion']
      end

      if attributes.has_key?(:'KubectlVersion')
        self.kubectl_version = attributes[:'KubectlVersion']
      end

      if attributes.has_key?(:'KustomizeVersion')
        self.kustomize_version = attributes[:'KustomizeVersion']
      end

      if attributes.has_key?(:'Platform')
        self.platform = attributes[:'Platform']
      end

      if attributes.has_key?(:'Version')
        self.version = attributes[:'Version']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          build_date == o.build_date &&
          compiler == o.compiler &&
          git_commit == o.git_commit &&
          git_tag == o.git_tag &&
          git_tree_state == o.git_tree_state &&
          go_version == o.go_version &&
          helm_version == o.helm_version &&
          jsonnet_version == o.jsonnet_version &&
          kubectl_version == o.kubectl_version &&
          kustomize_version == o.kustomize_version &&
          platform == o.platform &&
          version == o.version
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [build_date, compiler, git_commit, git_tag, git_tree_state, go_version, helm_version, jsonnet_version, kubectl_version, kustomize_version, platform, version].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = ArgoCD.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
