=begin
#Consolidate Services

#Description of all APIs

OpenAPI spec version: version not set

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.32-SNAPSHOT

=end

require 'uri'

module ArgoCD
  class SettingsServiceApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get returns Argo CD settings
    # @param [Hash] opts the optional parameters
    # @return [ClusterSettings]
    def settings_service_get(opts = {})
      data, _status_code, _headers = settings_service_get_with_http_info(opts)
      data
    end

    # Get returns Argo CD settings
    # @param [Hash] opts the optional parameters
    # @return [Array<(ClusterSettings, Fixnum, Hash)>] ClusterSettings data, response status code and response headers
    def settings_service_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SettingsServiceApi.settings_service_get ...'
      end
      # resource path
      local_var_path = '/api/v1/settings'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['argocd_auth']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'ClusterSettings')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SettingsServiceApi#settings_service_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Get returns Argo CD plugins
    # @param [Hash] opts the optional parameters
    # @return [ClusterSettingsPluginsResponse]
    def settings_service_get_plugins(opts = {})
      data, _status_code, _headers = settings_service_get_plugins_with_http_info(opts)
      data
    end

    # Get returns Argo CD plugins
    # @param [Hash] opts the optional parameters
    # @return [Array<(ClusterSettingsPluginsResponse, Fixnum, Hash)>] ClusterSettingsPluginsResponse data, response status code and response headers
    def settings_service_get_plugins_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: SettingsServiceApi.settings_service_get_plugins ...'
      end
      # resource path
      local_var_path = '/api/v1/settings/plugins'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['argocd_auth']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'ClusterSettingsPluginsResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SettingsServiceApi#settings_service_get_plugins\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
