=begin
#Consolidate Services

#Description of all APIs

OpenAPI spec version: version not set

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.32-SNAPSHOT

=end

require 'uri'

module ArgoCD
  class VersionServiceApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Version returns version information of the API server
    # @param [Hash] opts the optional parameters
    # @return [VersionVersionMessage]
    def version_service_version(opts = {})
      data, _status_code, _headers = version_service_version_with_http_info(opts)
      data
    end

    # Version returns version information of the API server
    # @param [Hash] opts the optional parameters
    # @return [Array<(VersionVersionMessage, Fixnum, Hash)>] VersionVersionMessage data, response status code and response headers
    def version_service_version_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: VersionServiceApi.version_service_version ...'
      end
      # resource path
      local_var_path = '/api/version'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['argocd_auth']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'VersionVersionMessage')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: VersionServiceApi#version_service_version\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
